server:
  port: 1234
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: Ambika@91
  jpa:
   hibernate:
    ddl-auto: create

      
  application:
    name: coupon-service
    

  

    
 