
server:
  port: 1111
#spring:
 # datasource:
#    url:  jdbc:mysql://localhost:4306/testdb
 #   username: root
 #   password: root
  #jpa:
 #   hibernate:
 #     ddl-auto: create
  #  show-sql: true
  #  properties:
  #   hibernate:
  #    format_sql: true
  #    dialect: org.hibernate.dialect.MySQL5Dialect
    
#spring.security.user.name
#spring.security.user.password


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
      base-path: /myactuator
      
      
  info:
    env:
      enabled: true
 
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
      
#info:
#  createdBy: Ambika
#  modifiedBy: 22ndjune2022
  

 
  
logging:
  level:
    com:
     zensar: debug
  
        