server:
  port: 4321

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: Ambika@91
  jpa:
   hibernate:
    ddl-auto: create

  
  

 

      


      
      
    
      
      
    